import Link from 'next/link';
import LayoutShell from '../components/LayoutShell';
import {courses} from '../data/mock';
export default function Home(){return <LayoutShell>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow"><i className="eyebrow-dot"/> SIH 2026 • Problem Statement 26101</span><h1>Build a future-ready statistical workforce.</h1><p>AI-powered competency assessment, personalized learning and intelligent assessment for professionals in India&apos;s Official Statistical System.</p><div className="hero-actions"><Link className="btn btn-primary" href="/dashboard">Explore Platform</Link><a className="btn btn-secondary" href="#how">How It Works</a></div><div className="hero-trust"><span className="pill">iGOT integration-ready</span><span className="pill">NSSTA / TPAC ready</span><span className="pill">Explainable AI</span><span className="pill">Accessibility-first</span></div></div><div className="hero-visual"><div className="dash-preview"><div className="dash-top"><strong>Competency Intelligence</strong><span>Demo dashboard • 12:42 PM</span></div><div className="preview-body"><div className="preview-grid"><div className="mini-panel"><span className="mini-title">Overall competency</span><div className="big-score"><div className="score-ring"><div className="score-text">67</div></div><div><strong style={{fontSize:14}}>Ananya Sharma</strong><div className="subtle">Senior Statistical Officer</div><div className="subtle">Labour Statistics</div></div></div><div className="bars"><div className="bar-row"><span>Statistical</span><div className="bar"><i style={{width:'82%'}}/></div><b>82</b></div><div className="bar-row"><span>Technical</span><div className="bar"><i style={{width:'61%'}}/></div><b>61</b></div><div className="bar-row"><span>Digital Gov</span><div className="bar"><i style={{width:'69%'}}/></div><b>69</b></div><div className="bar-row"><span>Behavioural</span><div className="bar"><i style={{width:'76%'}}/></div><b>76</b></div></div></div><div className="mini-panel"><span className="mini-title">Priority gaps</span><div className="mini-stack"><div className="mini-item"><b>Python · Level 2 → 4</b><span>High priority</span></div><div className="mini-item"><b>Sampling · Level 2 → 4</b><span>High priority</span></div><div className="mini-item"><b>Visualization · Level 3 → 4</b><span>Medium priority</span></div></div></div></div></div></div></div></div></section>
<section className="metrics"><div className="container metric-grid"><div className="metric"><strong>25+</strong><span>Competency domains in prototype taxonomy</span></div><div className="metric"><strong>100+</strong><span>Skill definitions and evidence types</span></div><div className="metric"><strong>500+</strong><span>Integration-ready learning resources</span></div><div className="metric"><strong>AI</strong><span>Assessment & recommendation engine</span></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><h2>One intelligence layer across the learning journey</h2><p>Designed to sit between workforce roles and the learning ecosystem so every recommendation has a reason, evidence and measurable outcome.</p></div></div><div className="cap-grid"><Cap n="01" t="AI Competency Intelligence" p="Build a role-aware competency profile using role, evidence, training history and assessment signals."/><Cap n="02" t="Automated Skill-Gap Analysis" p="Compare current capability against required levels and surface the gaps that matter most."/><Cap n="03" t="Personalized Learning Pathways" p="Combine digital learning with structured domain training and hands-on practice."/><Cap n="04" t="AI Assessment Studio" p="Generate traceable MCQs and quizzes from approved learning material, then measure competency improvement."/></div></div></section>
<section className="section alt" id="how"><div className="container"><div className="section-head"><div><h2>How StatSaksham works</h2><p>A structured government-style process designed around explainability and continuous capacity building.</p></div></div><div className="process">{[['01','Profile'],['02','Role Mapping'],['03','Assess'],['04','Find Gaps'],['05','Recommend'],['06','Reassess'],['07','Improve']].map(([n,t])=><div className="process-step" key={n}><b>{n}</b><span>{t}</span></div>)}</div></div></section>
<section className="section cream"><div className="container"><div className="section-head"><div><h2>See the learning path, not just a course list</h2><p>Recommendations combine competency coverage, role relevance, difficulty fit and transparent reasons.</p></div><Link href="/learning-path" className="btn btn-secondary">View Learning Path</Link></div><div className="path">{courses.slice(0,5).map((c,i)=><div className="path-card" key={c.id}><small>STEP {i+1} · {c.provider}</small><h4>{c.title}</h4><p>{c.competency} · {c.duration}</p></div>)}</div></div></section>
<section className="section"><div className="container split"><div className="panel panel-pad"><div className="section-label">Workforce intelligence</div><h2 style={{margin:'0 0 8px',fontSize:28}}>From one learner to an organization-wide view.</h2><p className="muted">Administrators can see competency distribution, priority gaps, training effectiveness and emerging skills without losing sight of the underlying evidence.</p><div className="spacer16"/><Link href="/admin/dashboard" className="btn btn-primary">Open Workforce Dashboard</Link></div><div className="panel panel-pad"><div className="section-label">Source traceability</div><h3 style={{marginTop:0}}>Every AI question has a trail.</h3><div className="why-box"><strong>Question 04 · APIs & Open Data</strong><p>Source: uploaded training material — Page 14. Answer confidence: 93%. Trainer review is required before publication.</p></div><div className="spacer16"/><Link href="/assessment-generator" className="btn btn-secondary">Open Assessment Studio</Link></div></div></section>
</LayoutShell>}
function Cap({n,t,p}:{n:string,t:string,p:string}){return <div className="cap-card"><div className="num">{n}</div><h3>{t}</h3><p>{p}</p></div>}
